### ISSUE TITLE
add link to source repo somewhere on homepage

### ISSUE THREAD

**Issue by reshamas** [pymc-devs/pymcon_2022_website#10]
Add link to source repo somewhere on homepage

So folks can submit or open an issue related to the website. 

Right now, the GitHub icon at bottom right links to:  
https://github.com/pymc-devs/pymc

**Comment by purna135** [comment]
What is the best place to give a link to repo ?

**Comment by purna135** [comment]
Can we include a section in the footer that lists all of the resources, including #14 and #17?
Like bellow: 

![image](https://user-images.githubusercontent.com/42216008/197764186-1f92945a-15a9-44ca-b314-f3a6cb2328c7.png)

**Comment by purna135** [comment]
> What should be the best place to give a link to the repo?

@canyon289 could you provide your input on this?

**Comment by canyon289** [comment]
change the link for the GitHub icon on the website to point to the webpage repo as Reshma suggested! it's a great idea
