### ISSUE TITLE
add a link to logos

### ISSUE THREAD

**Issue by reshamas** [pymc-devs/pymcon_2022_website#14]
Should we add a link to the PyMCon 2022 logos on the website, in case folks want to add it to their slide presentation, etc?

**Comment by purna135** [comment]
Hello, @reshamas. Can we include the PyMCon logos in the brand repository, https://github.com/pymc-devs/brand?

I simply need a link that contains PyMCon logos and branding guidelines.

**Comment by reshamas** [comment]
@purna135 
Yes, someone can submit a PR to this repo to add PyMCon logos:
[PyMCon'22 Web Series](https://github.com/pymc-devs/brand)

Best route:
create a folder "/pymcon-logos/"

cc:  @cuchoi
