### ISSUE TITLE
Add FAQ: what is the branding guide for PyMC?

### ISSUE THREAD

**Issue by reshamas** [pymc-devs/pymcon_2022_website#17]
Answer:
Branding guide is here:
https://github.com/pymc-devs/brand

**Comment by purna135** [comment]
Hi @reshamas.
I got this colour palette from the repo you provided; could you please share the colour codes for the remaining colours?
Only two colour codes are mentioned there, but the palette below contains seven colours; if you can assist me in obtaining the remaining codes, I will try to use them on the website.

I attempted to get the code using a colour picker, but it appears inaccurate.

![image](https://user-images.githubusercontent.com/42216008/198232315-28cdfb2d-2196-4c5e-beb8-457de455104b.png)
