### ISSUE TITLE
Include donation info

### ISSUE THREAD

**Issue by reshamas** [pymc-devs/pymcon_2022_website#20]
Can we include a page / section on "Donations / Support"?

The donations will be handled by NumFOCUS which is 501(c)(3) non profit and manages all finances for PyMC.

## Donations
Donations can be made in these ways:
1. PyMC Open Collective 
- https://opencollective.com/pymc
- Payment options:  credit card
- Pros: your company name appears as a donor
2. NumFOCUS
- https://numfocus.org/donate-to-pymc
- Payment options:  credit card, eCheck, PayPal
- Pros: your name appears in annual report 
3. Benevity
- [info to be added]

## Support
You can also support the PyMC project by purchasing swag from our official store. All net proceeds go to the project:
https://numfocus.myspreadshop.com/pymc+official+logo?idea=61f03c1df33f941d0307b965

**Comment by purna135** [comment]
@canyon289 
Do need a separate page for this? or can we create a section (for example below the "our sponsors" section on the homepage)?
