### ISSUE TITLE
website "not secure"

### ISSUE THREAD

**Issue by reshamas** [pymc-devs/pymcon_2022_website#23]
It says the website is not secure.

<img width="336" alt="Screen Shot 2022-10-28 at 10 11 08 AM" src="https://user-images.githubusercontent.com/2507232/198635596-72055ed3-a718-479e-a597-f652d9c32c9b.png">

**Comment by purna135** [comment]
Is it due to the SSL certificate?

**Comment by purna135** [comment]
The website seems secure now, so closing this issue.
