### ISSUE TITLE
Adding Twitter cards

### ISSUE THREAD

**Issue by cuchoi** [pymc-devs/pymcon_2022_website#24]
Probably falls more on the "nice to have" category, so feel free to ignore this request.

Could we add [Twitter cards](https://gohugo.io/templates/internal/#twitter-cards) to the website? Something simple: the image could always be the PyMCon logo.

Currently, the CFP link looks like this on Twitter:
<img width="537" alt="image" src="https://user-images.githubusercontent.com/1595942/198755184-fe0cd550-a9a6-46ec-a166-155b2988173c.png">

**Comment by canyon289** [comment]
yes please do
